/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mvc.lec01.dec30th.view;
import java.util.logging.Level;
import java.util.logging.Logger;
import mvc.lec01.dec30th.controler.CustomerControler;
import mvc.lec01.dec30th.dto.CustomerDto;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 * User Interface(UI) and function connectivity with other class
 * @author kavindi
 */
public class CustomerView extends javax.swing.JFrame {

    private CustomerControler customerControler; 
    /**
     * Creates new form CustomerView
     */
    public CustomerView() {
        customerControler = new CustomerControler();
        initComponents();
        loadCustomers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        TitleLable = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        custID = new javax.swing.JLabel();
        textID = new javax.swing.JTextField();
        salary = new javax.swing.JLabel();
        textsalary = new javax.swing.JTextField();
        textitle = new javax.swing.JTextField();
        title = new javax.swing.JLabel();
        city = new javax.swing.JLabel();
        textcity = new javax.swing.JTextField();
        textzip = new javax.swing.JTextField();
        dob = new javax.swing.JLabel();
        zip = new javax.swing.JLabel();
        textaname = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        textAddress = new javax.swing.JTextField();
        province = new javax.swing.JLabel();
        textprovince = new javax.swing.JTextField();
        textdob = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TitleLable.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TitleLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLable.setText("Customer Manage");

        custID.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        custID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        custID.setText("Cust ID");
        custID.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        textID.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        textID.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        salary.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        salary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salary.setText("Salary");
        salary.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        textsalary.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        textsalary.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        textitle.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        textitle.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        title.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Title");
        title.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        city.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        city.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        city.setText("City");
        city.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        textcity.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        textcity.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        textzip.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        textzip.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dob.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        dob.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dob.setText("DOB");
        dob.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        zip.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        zip.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        zip.setText("Postal Code");
        zip.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        textaname.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        textaname.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        name.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("Name");
        name.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        Address.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        Address.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Address.setText("Address");
        Address.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        textAddress.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        textAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        province.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        province.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        province.setText("Province");
        province.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        textprovince.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        textprovince.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        textdob.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        textdob.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textdob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textdobActionPerformed(evt);
            }
        });

        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCustomerMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCustomer);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TitleLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(custID, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(salary, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textsalary, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textitle, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textaname, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textdob, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(textAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zip))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textcity, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(province, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textprovince, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textzip, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(15, 15, 15)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnsave)
                        .addGap(64, 64, 64)))
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleLable, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(custID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(textaname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textdob, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salary, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textsalary, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(zip, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textzip, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(textcity, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(province, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textprovince, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsave)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textdobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textdobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textdobActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
         saveCustomer();
        
    }//GEN-LAST:event_btnsaveActionPerformed

    private void tblCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomerMouseClicked
        searchCustomer();
    }//GEN-LAST:event_tblCustomerMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        updateCustomer();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        deleteCustomer();
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
   
  
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JLabel TitleLable;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnsave;
    private javax.swing.JLabel city;
    private javax.swing.JLabel custID;
    private javax.swing.JLabel dob;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel province;
    private javax.swing.JLabel salary;
    private javax.swing.JTable tblCustomer;
    private javax.swing.JTextField textAddress;
    private javax.swing.JTextField textID;
    private javax.swing.JTextField textaname;
    private javax.swing.JTextField textcity;
    private javax.swing.JTextField textdob;
    private javax.swing.JTextField textitle;
    private javax.swing.JTextField textprovince;
    private javax.swing.JTextField textsalary;
    private javax.swing.JTextField textzip;
    private javax.swing.JLabel title;
    private javax.swing.JLabel zip;
    // End of variables declaration//GEN-END:variables

    private void saveCustomer() {
       
        CustomerDto dto = new CustomerDto();
        dto.setCustID(textID.getText());
        dto.setTitle(textitle.getText());
        dto.setName(textaname.getText());
        dto.setDob(textdob.getText());
        dto.setSalary(Double.parseDouble(textsalary.getText()));
        dto.setAddress(textAddress.getText());
        dto.setCity(textcity.getText());
        dto.setProvince(textprovince.getText());
        dto.setZip(textzip.getText());
        
        try {
            String result = customerControler.saveCustomer(dto);
            System.out.println(result);
            JOptionPane.showMessageDialog(this, result);
            loadCustomers();
            clear();
            
        } catch (Exception ex) {
            System.out.println("file not found");
            System.out.println(ex.getMessage());
             JOptionPane.showMessageDialog(this,ex.getMessage());
        } 
    }
    
    private void clear() {
          
        textID.setText("");
        textitle.setText("");
        textaname.setText("");
        textdob.setText("");
        textsalary.setText("");
        textAddress.setText("");
        textcity.setText("");
        textprovince.setText("");
        textzip.setText("");
      
    }

    private void loadCustomers() {
        try {
            String columns[] = {"ID","Name","Address","Salary","Postal Code"};
            DefaultTableModel dtm = new DefaultTableModel(columns, 0){
                @Override
                public boolean isCellEditable(int row, int column){
                    return false;}
            };
            
            tblCustomer.setModel(dtm);
            
            ArrayList<CustomerDto> customerDtos = customerControler.getAllCustomer();
            
            for (CustomerDto customerDto : customerDtos) {
                Object[] rowData = {customerDto.getCustID(), customerDto.getTitle() + " " + customerDto.getName(),
                customerDto.getAddress() + ", " + customerDto.getCity(), customerDto.getSalary(), customerDto.getZip()};
                dtm.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
    }

    private void searchCustomer() {
        String id = tblCustomer.getValueAt(tblCustomer.getSelectedRow(),0).toString();
    
        try {
            CustomerDto dto = customerControler.searchCustomer(id);
            
            if(dto != null){
                textID.setText(dto.getCustID());
                textitle.setText(dto.getTitle());
                textaname.setText(dto.getName());
                textdob.setText(dto.getDob());
                textsalary.setText(Double.toString(dto.getSalary()));
                textAddress.setText(dto.getAddress());
                textcity.setText(dto.getCity());
                textprovince.setText(dto.getProvince());
                textzip.setText(dto.getZip());
            }
            else{
                JOptionPane.showMessageDialog(this, "Customer Not Found");
            }   
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    
    
    
    }

    private void updateCustomer() {
       
        try {
            CustomerDto dto = new CustomerDto();
            dto.setCustID(textID.getText());
            dto.setTitle(textitle.getText());
            dto.setName(textaname.getText());
            dto.setDob(textdob.getText());
            dto.setSalary(Double.parseDouble(textsalary.getText()));
            dto.setAddress(textAddress.getText());
            dto.setCity(textcity.getText());
            dto.setProvince(textprovince.getText());
            dto.setZip(textzip.getText());
            
            String resp = customerControler.updateCustomer(dto);
            JOptionPane.showMessageDialog(this, resp);
            loadCustomers();
            clear();
        } catch (Exception ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    
    }

    private void deleteCustomer() {
        try {
            String id = textID.getText();
            String resp = customerControler.deleteCustomer(id);   
            JOptionPane.showMessageDialog(this, resp);
            loadCustomers();
            clear();
            
        } catch (Exception ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
    
    

  
    
    

    
}
